title: Hilmy's Blog # The title of the blog
author: Muhammad Naufal Hilmy Makarim # Your name 
email: naufal[at]hilmy[dot]dev # your email shown in the footer
email_link: naufal@hilmy.dev
url: http://hilmy.dev/blog # this is your site's root address.
header: Hi!
description: > # this means to ignore newlines until "show_excerpts:"
  I am Hilmy, and this is my blog 😬
favicon: "./favicon.ico" # set the favicon of the site 
post_img: https://raw.githubusercontent.com/mnaufalhilmym/blog/main/assets/img/_posts

show_excerpts: false # set to true to show excerpts on the homepage
  
# Moving date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
moving:
  avatar_url: "assets/img/1623630178478.jpg" # avatar in about page
  about_you: Human being who loves Linux and code # short description about you in about page
  date_format: "%b %d" # date format of posts in home page
  back_to: "Home" # In the post page, you have a back button above the title, you can custom the text by yourself.

  # generate social links in about page.
  social_links:
    # twitter: 
    github:  mnaufalhilmym
    rss: RSS
    # dribbble: 
    facebook: mnaufalhilmym
    # flickr:   
    # instagram: 
    linkedin: naufalhilmy
    # pinterest: 
    # youtube: 
    # youtube_channel: 
    # youtube_channel_name: 
    # telegram: 
    # googleplus: 
    # microdotblog: 
    # reddit: 

    # Mastodon instances
    # mastodon:
    # - username: 
    #   instance: 
    # - username: 
    #   instance: 

# Build settings
theme: moving # note, please use huangyz0918/moving if you want to publish to Github Pages.

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-target-blank
